# Nexus Repository and Nginx Reverse Proxy dockercompose.yaml file 

version: "3.8"
services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: always
    volumes:
      - "./nexus-data:/nexus-data"
        #- ./resolv.conf:/etc/resolv.conf:ro
    ports:
      - "8081:8081"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
      - "5005:5005"
      - "5006:5006"
      - "9090:9090"
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx-configs/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-configs/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
      - "8882:8882"
    depends_on:
      - nexus

